services:
  user-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: connectsphere
      MYSQL_DATABASE: user
      MYSQL_USER: connectsphere
      MYSQL_PASSWORD: connectsphere
    ports:
      - "3307:3306"
    volumes:
      - user_data:/var/lib/mysql
      - ./mysql/init/user.sql:/docker-entrypoint-initdb.d/01-user.sql

  event-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: connectsphere
      MYSQL_DATABASE: event
      MYSQL_USER: connectsphere
      MYSQL_PASSWORD: connectsphere
    ports:
      - "3309:3306"
    volumes:
      - event_data:/var/lib/mysql
      - ./mysql/init/event.sql:/docker-entrypoint-initdb.d/01-event.sql

  venue-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: connectsphere
      MYSQL_DATABASE: venue
      MYSQL_USER: connectsphere
      MYSQL_PASSWORD: connectsphere
    ports:
      - "3308:3306"
    volumes:
      - venue_data:/var/lib/mysql
      - ./mysql/init/venue.sql:/docker-entrypoint-initdb.d/01-venue.sql

  equipment-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: connectsphere
      MYSQL_DATABASE: equipment
      MYSQL_USER: connectsphere
      MYSQL_PASSWORD: connectsphere
    ports:
      - "3310:3306"
    volumes:
      - equipment_data:/var/lib/mysql
      - ./mysql/init/equipment.sql:/docker-entrypoint-initdb.d/01-equipment.sql

  registration-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: connectsphere
      MYSQL_DATABASE: registration
      MYSQL_USER: connectsphere
      MYSQL_PASSWORD: connectsphere
    ports:
      - "3311:3306"
    volumes:
      - registration_data:/var/lib/mysql
      - ./mysql/init/registration.sql:/docker-entrypoint-initdb.d/01-registration.sql

  notification-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: connectsphere
      MYSQL_DATABASE: notification
      MYSQL_USER: connectsphere
      MYSQL_PASSWORD: connectsphere
    ports:
      - "3312:3306"
    volumes:
      - notification_data:/var/lib/mysql
      - ./mysql/init/notification.sql:/docker-entrypoint-initdb.d/01-notification.sql

volumes:
  user_data:
  event_data:
  venue_data:
  equipment_data:
  registration_data:
  notification_data:
