"""venue AC1 fields

Revision ID: 592d30ed28e4
Revises: 0001_initial
Create Date: 2026-09-21 18:57:09.250942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '592d30ed28e4'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('code', sa.String(length=64), nullable=False))
    op.add_column('venues', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('floor', sa.String(length=64), nullable=False))
    op.add_column('venues', sa.Column('description', sa.Text(), nullable=False))
    op.alter_column('venues', 'accessibility',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('venues', 'operating_hours',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'operating_hours',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('venues', 'accessibility',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'floor')
    op.drop_column('venues', 'address')
    op.drop_column('venues', 'code')
    # ### end Alembic commands ###
