"""venue AC1 fields

Revision ID: 592d30ed28e4
Revises: 0001_initial
Create Date: 2026-09-21 18:57:09.250942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '592d30ed28e4'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('venues', sa.Column('code', sa.String(length=64), nullable=False))
    op.add_column('venues', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('floor', sa.String(length=64), nullable=False))
    op.add_column('venues', sa.Column('description', sa.Text(), nullable=False))

    # Existing installations stored these as human-readable strings. MySQL
    # requires every existing value to be valid JSON before altering a column
    # to JSON, so preserve legacy values in the new list-shaped structures.
    op.execute(
        """
        UPDATE venues
        SET accessibility = JSON_ARRAY(accessibility)
        WHERE NOT JSON_VALID(accessibility)
        """
    )
    op.execute(
        """
        UPDATE venues
        SET operating_hours = JSON_ARRAY(
            JSON_OBJECT('day', 'Legacy', 'opens', '', 'closes', operating_hours)
        )
        WHERE NOT JSON_VALID(operating_hours)
        """
    )
    op.alter_column('venues', 'accessibility',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('venues', 'operating_hours',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'operating_hours',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('venues', 'accessibility',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'floor')
    op.drop_column('venues', 'address')
    op.drop_column('venues', 'code')
    # ### end Alembic commands ###
