"""venue booking request snapshot notes and warnings

Revision ID: 67ee92bd65e7
Revises: 7716fef713c2
Create Date: 2026-09-29 14:13:59.598132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67ee92bd65e7'
down_revision: Union[str, None] = '7716fef713c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_bookings', sa.Column('event_snapshot', sa.JSON(), nullable=True))
    op.add_column('venue_bookings', sa.Column('coordinator_notes', sa.Text(), nullable=True))
    op.add_column('venue_bookings', sa.Column('warnings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue_bookings', 'warnings')
    op.drop_column('venue_bookings', 'coordinator_notes')
    op.drop_column('venue_bookings', 'event_snapshot')
    # ### end Alembic commands ###
