"""venue activity log changed-by name and role

Revision ID: 7716fef713c2
Revises: 79f124a3ebec
Create Date: 2026-09-22 16:17:51.440309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7716fef713c2'
down_revision: Union[str, None] = '79f124a3ebec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (nullable=False needs a value for them);
    # the ORM's own default="" covers new rows going forward.
    op.add_column(
        'venue_activity_log',
        sa.Column('changed_by_name', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column(
        'venue_activity_log',
        sa.Column('changed_by_role', sa.String(length=64), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue_activity_log', 'changed_by_role')
    op.drop_column('venue_activity_log', 'changed_by_name')
    # ### end Alembic commands ###
