"""venue activity log AC9

Revision ID: 79f124a3ebec
Revises: b779312d8986
Create Date: 2026-09-21 21:24:06.722142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '79f124a3ebec'
down_revision: Union[str, None] = 'b779312d8986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_activity_log',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('venue_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_activity_log')
    # ### end Alembic commands ###
