"""compute venue capacity from layouts (AC3)

Revision ID: b779312d8986
Revises: 592d30ed28e4
Create Date: 2026-09-21 20:40:52.036477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'b779312d8986'
down_revision: Union[str, None] = '592d30ed28e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
